/* Multi-shape overlay editor. Coordinates are stored as image fractions so
   shapes remain aligned after zoom, resize, and history changes. */
(() => {
  const $ = id => document.getElementById(id);
  const img = $('previewImage'), wrap = $('previewImageWrapper'), tab = $('tab-shapes');
  if (!img || !wrap || !tab) return;
  const c = document.createElement('canvas'); c.className = 'shape-overlay'; c.hidden = true; wrap.appendChild(c);
  const x = c.getContext('2d'); let items=[], selected=null, copy=null, drawing=null, drag=null, type='rect';
  const val = id => $(id).value;
  const style = () => ({fill:val('shapeFill'), stroke:val('shapeStroke'), mode:val('shapeFillMode'), sw:+val('shapeStrokeWidth'), alpha:+val('shapeOpacity')/100, glow:$('shapeGlow').checked, bevel:$('shape3d').checked, text:val('shapeText'), textColor:val('shapeTextColor'), rotate:+val('shapeRotate')});
  function rect(){ const r=img.getBoundingClientRect(), w=wrap.getBoundingClientRect(); c.width=Math.max(1,Math.round(r.width));c.height=Math.max(1,Math.round(r.height));c.style.left=(r.left-w.left)+'px';c.style.top=(r.top-w.top)+'px';c.style.width=r.width+'px';c.style.height=r.height+'px'; }
  function path(s,ctx){const X=s.x*c.width,Y=s.y*c.height,W=s.w*c.width,H=s.h*c.height;ctx.beginPath();if(s.type==='circle')ctx.ellipse(X+W/2,Y+H/2,Math.abs(W/2),Math.abs(H/2),0,0,7);else if(s.type==='triangle'){ctx.moveTo(X+W/2,Y);ctx.lineTo(X+W,Y+H);ctx.lineTo(X,Y+H);ctx.closePath()}else if(s.type==='star'){for(let i=0;i<10;i++){let a=-Math.PI/2+i*Math.PI/5,r=i%2?Math.min(Math.abs(W),Math.abs(H))*.2:Math.min(Math.abs(W),Math.abs(H))*.5;let px=X+W/2+Math.cos(a)*r,py=Y+H/2+Math.sin(a)*r;i?ctx.lineTo(px,py):ctx.moveTo(px,py)}ctx.closePath()}else if(s.type==='arrow'){ctx.moveTo(X,Y+H*.3);ctx.lineTo(X+W*.62,Y+H*.3);ctx.lineTo(X+W*.62,Y);ctx.lineTo(X+W,Y+H/2);ctx.lineTo(X+W*.62,Y+H);ctx.lineTo(X+W*.62,Y+H*.7);ctx.lineTo(X,Y+H*.7);ctx.closePath()}else if(s.type==='freehand'){(s.points||[]).forEach((p,i)=>i?ctx.lineTo(p.x*c.width,p.y*c.height):ctx.moveTo(p.x*c.width,p.y*c.height))}else if(s.type==='roundRect'){ctx.roundRect(X,Y,W,H,Math.min(Math.abs(W),Math.abs(H))*.16)}else ctx.rect(X,Y,W,H)}
  function draw(){rect();x.clearRect(0,0,c.width,c.height);items.forEach(s=>{x.save();x.translate((s.x+s.w/2)*c.width,(s.y+s.h/2)*c.height);x.rotate((s.rotate||0)*Math.PI/180);x.translate(-(s.x+s.w/2)*c.width,-(s.y+s.h/2)*c.height);x.globalAlpha=s.alpha;if(s.glow){x.shadowColor=s.fill;x.shadowBlur=16}if(s.mode==='gradient'){let g=x.createLinearGradient(s.x*c.width,s.y*c.height,(s.x+s.w)*c.width,(s.y+s.h)*c.height);g.addColorStop(0,s.fill);g.addColorStop(1,s.stroke);x.fillStyle=g}else x.fillStyle=s.fill;x.strokeStyle=s.stroke;x.lineWidth=s.sw;path(s,x);if(s.type==='freehand')x.stroke();else{x.fill();x.stroke()}if(s.bevel&&s.type!=='freehand'){x.globalAlpha=s.alpha*.35;x.strokeStyle='#fff';x.lineWidth=Math.max(1,s.sw/2);path(s,x);x.stroke()}if(s.text){x.shadowBlur=0;x.globalAlpha=s.alpha;x.fillStyle=s.textColor||'#fff';x.font=`700 ${Math.max(14,Math.abs(s.h*c.height)*.24)}px Inter,sans-serif`;x.textAlign='center';x.textBaseline='middle';x.fillText(s.text,(s.x+s.w/2)*c.width,(s.y+s.h/2)*c.height,Math.abs(s.w*c.width)*.88)}if(s===selected){x.shadowBlur=0;x.globalAlpha=1;x.strokeStyle='#00d4c8';x.setLineDash([6,4]);x.lineWidth=2;x.strokeRect(s.x*c.width-4,s.y*c.height-4,s.w*c.width+8,s.h*c.height+8)}x.restore()})}
  function add(){let s={type,...style(),x:.3,y:.3,w:.25,h:.18};items.push(s);selected=s;draw()}
  function point(e){let r=c.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width,y:(e.clientY-r.top)/r.height}}
  c.addEventListener('pointerdown',e=>{let p=point(e);if(type==='freehand'){drawing={type,...style(),x:p.x,y:p.y,w:.01,h:.01,points:[p]};items.push(drawing);selected=drawing}else{selected=[...items].reverse().find(s=>p.x>=s.x&&p.x<=s.x+s.w&&p.y>=s.y&&p.y<=s.y+s.h);drag=selected&&{dx:p.x-selected.x,dy:p.y-selected.y}}draw();c.setPointerCapture(e.pointerId)});
  c.addEventListener('pointermove',e=>{let p=point(e);if(drawing){drawing.points.push(p);draw()}else if(drag){selected.x=Math.max(0,Math.min(1-selected.w,p.x-drag.dx));selected.y=Math.max(0,Math.min(1-selected.h,p.y-drag.dy));draw()}});c.addEventListener('pointerup',()=>{drawing=null;drag=null});
  $('shapePresetGrid').addEventListener('click',e=>{let b=e.target.closest('[data-shape]');if(!b)return;type=b.dataset.shape;document.querySelectorAll('#shapePresetGrid button').forEach(q=>q.classList.toggle('active',q===b));if(type!=='freehand')add()});
  $('shapeAddBtn').onclick=add;$('shapeDuplicateBtn').onclick=()=>{if(selected){copy=JSON.parse(JSON.stringify(selected));copy.x=Math.min(.9,copy.x+.03);copy.y=Math.min(.9,copy.y+.03);items.push(copy);selected=copy;draw()}};$('shapeDeleteBtn').onclick=()=>{if(selected){items=items.filter(s=>s!==selected);selected=null;draw()}};
  ['shapeFill','shapeStroke','shapeFillMode','shapeStrokeWidth','shapeOpacity','shapeGlow','shape3d','shapeText','shapeTextColor','shapeRotate'].forEach(id=>$(id).addEventListener('input',()=>{if(selected){Object.assign(selected,style());draw()}$('shapeStrokeWidthValue').textContent=val('shapeStrokeWidth');$('shapeOpacityValue').textContent=val('shapeOpacity');$('shapeRotateValue').textContent=val('shapeRotate')}));
  $('shapeSize').addEventListener('input',()=>{if(!selected)return;const scale=+val('shapeSize')/(selected._baseSize||100);selected.w*=scale;selected.h*=scale;selected._baseSize=+val('shapeSize');$('shapeSizeValue').textContent=val('shapeSize');draw()});
  document.addEventListener('keydown',e=>{if(!tab.classList.contains('active')||['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='c'&&selected){copy=JSON.parse(JSON.stringify(selected));e.preventDefault()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='v'&&copy){let n=JSON.parse(JSON.stringify(copy));n.x=Math.min(.9,n.x+.03);n.y=Math.min(.9,n.y+.03);items.push(n);selected=n;draw();e.preventDefault()}if(e.key==='Delete'){items=items.filter(s=>s!==selected);selected=null;draw()}});
  document.addEventListener('app:tabchange',()=>{c.hidden=!tab.classList.contains('active');if(!c.hidden)draw()}); img.addEventListener('load',draw);window.addEventListener('resize',draw);
  window.shapeEditor={hasShapes:()=>items.length>0,drawTo:(ctx,w,h)=>{const oldW=c.width,oldH=c.height;c.width=w;c.height=h;items.forEach(s=>{let z={...s};ctx.save();ctx.translate((z.x+z.w/2)*w,(z.y+z.h/2)*h);ctx.rotate((z.rotate||0)*Math.PI/180);ctx.translate(-(z.x+z.w/2)*w,-(z.y+z.h/2)*h);ctx.globalAlpha=z.alpha;if(z.mode==='gradient'){let g=ctx.createLinearGradient(z.x*w,z.y*h,(z.x+z.w)*w,(z.y+z.h)*h);g.addColorStop(0,z.fill);g.addColorStop(1,z.stroke);ctx.fillStyle=g}else ctx.fillStyle=z.fill;ctx.strokeStyle=z.stroke;ctx.lineWidth=z.sw*(w/(oldW||w));if(z.glow){ctx.shadowColor=z.fill;ctx.shadowBlur=16*(w/(oldW||w))}path(z,ctx);z.type==='freehand'?ctx.stroke():(ctx.fill(),ctx.stroke());if(z.bevel&&z.type!=='freehand'){ctx.shadowBlur=0;ctx.globalAlpha=z.alpha*.35;ctx.strokeStyle='#fff';ctx.lineWidth=Math.max(1,z.sw/2);path(z,ctx);ctx.stroke()}if(z.text){ctx.shadowBlur=0;ctx.globalAlpha=z.alpha;ctx.fillStyle=z.textColor||'#fff';ctx.font=`700 ${Math.max(14,Math.abs(z.h*h)*.24)}px Inter`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(z.text,(z.x+z.w/2)*w,(z.y+z.h/2)*h)}ctx.restore()});c.width=oldW;c.height=oldH;draw()}};
})();
